import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import firebase from 'firebase/compat/app'
import GetPumps from '../../components/cloudFirestore/GetPumps'
import Link from 'next/link'


export default function Pumps() {
  // const {user} = useAuth()
  // const [user,loading,error] = useAuthState(firebase.auth())
  // console.log("Loading:" + loading + "|" + "Current User:" + user)

  // if(user){
    return (
      <>
        <container className={styles.main}>
            <>Select Pump</>
            <GetPumps/>
        </container>  
      </>
    )
  // } 

  // else return (
  //   <div className={styles.container}>
  
  //     <Head>
  //       <title>Create Next App</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>

  //     <footer className={styles.footer}>
  //       <Link
  //         href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //         target="_blank"
  //         rel="noopener noreferrer"
  //       >
  //         Powered by{' '}
  //         <span className={styles.logo}>
  //           <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
  //         </span>
  //       </Link>
  //     </footer>
  //   </div>
  // )
}
