import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import firebase from 'firebase/compat/app'
import WriteToCloudFirestore from '../components/cloudFirestore/Write'
import ReadFromCloudFirestore from '../components/cloudFirestore/Read'
import GetPumps from '../components/cloudFirestore/GetPumps'
import Counter from '../components/realtimeDatabase/Counter'
import UploadImageWithData from '../components/storage/UploadImageWithData'
import ReadImageWithData from '../components/cloudFirestore/ReadImageWithDataFiles'
import LogoutButton from '../components/auth/LogoutButton'
import useAuth from '../firebase/useAuth'

export default function Home() {
  // const {user} = useAuth()
  // const [user,loading,error] = useAuthState(firebase.auth())
  // console.log("Loading:" + loading + "|" + "Current User:" + user)

  // if(user){
    function goToUploadCSVPage () {
      window.location.href='/upload_csv';
    }

    return (
      <>
        <container className={styles.main}>
          {/* <h1>{user.name}</h1>
          <h3>{user.email}</h3>
          {user.profilePic? <image src={user.profilePic} height={50} width={50}></image> : <p>No Profile Picture</p>} */}
          {/* <WriteToCloudFirestore />
          <ReadImageWithData />
          <Counter id={user.id}/> */}
          {/* <UploadImageWithData /> */}
          <GetPumps/>
          <button onClick={goToUploadCSVPage}>Upload CSV</button>
          <LogoutButton />
        </container>  
      </>
    )
  // } 

  // else return (
  //   <div className={styles.container}>
  
  //     <Head>
  //       <title>Create Next App</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>

  //     <footer className={styles.footer}>
  //       <Link
  //         href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //         target="_blank"
  //         rel="noopener noreferrer"
  //       >
  //         Powered by{' '}
  //         <span className={styles.logo}>
  //           <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
  //         </span>
  //       </Link>
  //     </footer>
  //   </div>
  // )
}
