import Head from 'next/head'
import Image from 'next/image'
import styles from '../../../styles/Home.module.css'
import firebase from 'firebase/compat/app'
// import useAuth from '../../../firebase/useAuth'
import AddImages from '../../../components/cloudFirestore/AddImages'

export default function AddImage() {
  // const {user} = useAuth()
  // const [user,loading,error] = useAuthState(firebase.auth())
  // console.log("Loading:" + loading + "|" + "Current User:" + user)

  // if(user){
    return (
      <>
        <container>
          <AddImages/>
        </container>  
      </>
    )
  // } 

  // else return (
  //   <div className={styles.container}>
  
  //     <Head>
  //       <title>Create Next App</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>
  //   </div>
  // )
}
